nome: str = (input('Digite seu nome completo: ')).strip()
print('Analisando seu nome, ele: ')
print('Em maisculas, escreve-se {}'.format(nome.upper()))
print('Em minúsculas, escreve-se{}:'.format(nome.lower()))
print('Seu nome tem {} letras'.format(len(nome) - nome.count(' ')))
print('Seu primeiro nome tem {} letras'.format(nome.find(" ")))
separa = nome.split()
print('Seu primeiro nome é {} e ele tem {} letras'.format(separa[0], len(separa[0])))
print(nome.capitalize())
print(nome.title())
print(nome.split())